// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: e4fc1a244f2240fc

import { callMCPToolTyped } from "codegen/runtime";

export interface CreateuserParams {

  body: {

    name: string;

    email: string;
  };
}

export interface CreateuserResult Record<string, unknown>

export const toolMeta = {
  server: "demoapi",
  name: "createUser",
  description: "Create a new user"
};

/**
 * Create a new user
 */
export async function createuser(params: CreateuserParams): Promise<CreateuserResult> {
  return callMCPToolTyped<CreateuserParams, CreateuserResult>("demoapi__createUser", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
