// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: bbbc15efc969ee43

import { callMCPToolTyped } from "codegen/runtime";

export interface DeleteuserParams {

  path: {

    id: string;
  };
}

export interface DeleteuserResult Record<string, unknown>

export const toolMeta = {
  server: "demoapi",
  name: "deleteUser",
  description: "Delete user"
};

/**
 * Delete user
 */
export async function deleteuser(params: DeleteuserParams): Promise<DeleteuserResult> {
  return callMCPToolTyped<DeleteuserParams, DeleteuserResult>("demoapi__deleteUser", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
