// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: f6c658c6b439606d

import { callMCPToolTyped } from "codegen/runtime";

export interface GetuserParams {

  path: {

    id: string;
  };
}

export interface GetuserResult Record<string, unknown>

export const toolMeta = {
  server: "demoapi",
  name: "getUser",
  description: "Get user by ID"
};

/**
 * Get user by ID
 */
export async function getuser(params: GetuserParams): Promise<GetuserResult> {
  return callMCPToolTyped<GetuserParams, GetuserResult>("demoapi__getUser", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
