// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 7c0535808d5a941b

import { callMCPToolTyped } from "codegen/runtime";

export interface ListusersParams Record<string, unknown>

export interface ListusersResult Record<string, unknown>

export const toolMeta = {
  server: "demoapi",
  name: "listUsers",
  description: "List all users"
};

/**
 * List all users
 */
export async function listusers(params: ListusersParams): Promise<ListusersResult> {
  return callMCPToolTyped<ListusersParams, ListusersResult>("demoapi__listUsers", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
