// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: f4317482255800b5

import { callMCPToolTyped } from "codegen/runtime";

export interface UpdateuserParams {

  path: {

    id: string;
  };

  body: {

    name?: string;

    email?: string;
  };
}

export interface UpdateuserResult Record<string, unknown>

export const toolMeta = {
  server: "demoapi",
  name: "updateUser",
  description: "Update user"
};

/**
 * Update user
 */
export async function updateuser(params: UpdateuserParams): Promise<UpdateuserResult> {
  return callMCPToolTyped<UpdateuserParams, UpdateuserResult>("demoapi__updateUser", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
