// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 68342948fdae469d

import { callMCPToolTyped } from "codegen/runtime";

export interface CreateDirectoryParams Record<string, unknown>

export interface CreateDirectoryResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "create_directory",
  description: "Create a new directory or ensure a directory exists. Can create multiple nested directories in one operation. If the directory already exists, this operation will succeed silently. Perfect for setting up directory structures for projects or ensuring required paths exist. Only works within allowed directories."
};

/**
 * Create a new directory or ensure a directory exists. Can create multiple nested directories in one operation. If the directory already exists, this operation will succeed silently. Perfect for setting up directory structures for projects or ensuring required paths exist. Only works within allowed directories.
 */
export async function createDirectory(params: CreateDirectoryParams): Promise<CreateDirectoryResult> {
  return callMCPToolTyped<CreateDirectoryParams, CreateDirectoryResult>("filesystem__create_directory", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
