// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: ea284f9ae77dfbef

import { callMCPToolTyped } from "codegen/runtime";

export interface DirectoryTreeParams Record<string, unknown>

export interface DirectoryTreeResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "directory_tree",
  description: "Get a recursive tree view of files and directories as a JSON structure. Each entry includes 'name', 'type' (file/directory), and 'children' for directories. Files have no children array, while directories always have a children array (which may be empty). The output is formatted with 2-space indentation for readability. Only works within allowed directories."
};

/**
 * Get a recursive tree view of files and directories as a JSON structure. Each entry includes 'name', 'type' (file/directory), and 'children' for directories. Files have no children array, while directories always have a children array (which may be empty). The output is formatted with 2-space indentation for readability. Only works within allowed directories.
 */
export async function directoryTree(params: DirectoryTreeParams): Promise<DirectoryTreeResult> {
  return callMCPToolTyped<DirectoryTreeParams, DirectoryTreeResult>("filesystem__directory_tree", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
