// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: e11435e95b9cdf55

import { callMCPToolTyped } from "codegen/runtime";

export interface EditFileParams Record<string, unknown>

export interface EditFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "edit_file",
  description: "Make line-based edits to a text file. Each edit replaces exact line sequences with new content. Returns a git-style diff showing the changes made. Only works within allowed directories."
};

/**
 * Make line-based edits to a text file. Each edit replaces exact line sequences with new content. Returns a git-style diff showing the changes made. Only works within allowed directories.
 */
export async function editFile(params: EditFileParams): Promise<EditFileResult> {
  return callMCPToolTyped<EditFileParams, EditFileResult>("filesystem__edit_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
