// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: f7acb98e1d785913

import { callMCPToolTyped } from "codegen/runtime";

export interface GetFileInfoParams Record<string, unknown>

export interface GetFileInfoResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "get_file_info",
  description: "Retrieve detailed metadata about a file or directory. Returns comprehensive information including size, creation time, last modified time, permissions, and type. This tool is perfect for understanding file characteristics without reading the actual content. Only works within allowed directories."
};

/**
 * Retrieve detailed metadata about a file or directory. Returns comprehensive information including size, creation time, last modified time, permissions, and type. This tool is perfect for understanding file characteristics without reading the actual content. Only works within allowed directories.
 */
export async function getFileInfo(params: GetFileInfoParams): Promise<GetFileInfoResult> {
  return callMCPToolTyped<GetFileInfoParams, GetFileInfoResult>("filesystem__get_file_info", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
