// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: e755ae767c54ae68

import { callMCPToolTyped } from "codegen/runtime";

export interface ListAllowedDirectoriesParams Record<string, unknown>

export interface ListAllowedDirectoriesResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "list_allowed_directories",
  description: "Returns the list of directories that this server is allowed to access. Subdirectories within these allowed directories are also accessible. Use this to understand which directories and their nested paths are available before trying to access files."
};

/**
 * Returns the list of directories that this server is allowed to access. Subdirectories within these allowed directories are also accessible. Use this to understand which directories and their nested paths are available before trying to access files.
 */
export async function listAllowedDirectories(params: ListAllowedDirectoriesParams): Promise<ListAllowedDirectoriesResult> {
  return callMCPToolTyped<ListAllowedDirectoriesParams, ListAllowedDirectoriesResult>("filesystem__list_allowed_directories", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
