// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: e509628a53351779

import { callMCPToolTyped } from "codegen/runtime";

export interface ListDirectoryParams Record<string, unknown>

export interface ListDirectoryResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "list_directory",
  description: "Get a detailed listing of all files and directories in a specified path. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is essential for understanding directory structure and finding specific files within a directory. Only works within allowed directories."
};

/**
 * Get a detailed listing of all files and directories in a specified path. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is essential for understanding directory structure and finding specific files within a directory. Only works within allowed directories.
 */
export async function listDirectory(params: ListDirectoryParams): Promise<ListDirectoryResult> {
  return callMCPToolTyped<ListDirectoryParams, ListDirectoryResult>("filesystem__list_directory", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
