// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 412f3e23a5556460

import { callMCPToolTyped } from "codegen/runtime";

export interface ListDirectoryWithSizesParams Record<string, unknown>

export interface ListDirectoryWithSizesResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "list_directory_with_sizes",
  description: "Get a detailed listing of all files and directories in a specified path, including sizes. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is useful for understanding directory structure and finding specific files within a directory. Only works within allowed directories."
};

/**
 * Get a detailed listing of all files and directories in a specified path, including sizes. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is useful for understanding directory structure and finding specific files within a directory. Only works within allowed directories.
 */
export async function listDirectoryWithSizes(params: ListDirectoryWithSizesParams): Promise<ListDirectoryWithSizesResult> {
  return callMCPToolTyped<ListDirectoryWithSizesParams, ListDirectoryWithSizesResult>("filesystem__list_directory_with_sizes", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
