// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 404db42be0c10508

import { callMCPToolTyped } from "codegen/runtime";

export interface MoveFileParams Record<string, unknown>

export interface MoveFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "move_file",
  description: "Move or rename files and directories. Can move files between directories and rename them in a single operation. If the destination exists, the operation will fail. Works across different directories and can be used for simple renaming within the same directory. Both source and destination must be within allowed directories."
};

/**
 * Move or rename files and directories. Can move files between directories and rename them in a single operation. If the destination exists, the operation will fail. Works across different directories and can be used for simple renaming within the same directory. Both source and destination must be within allowed directories.
 */
export async function moveFile(params: MoveFileParams): Promise<MoveFileResult> {
  return callMCPToolTyped<MoveFileParams, MoveFileResult>("filesystem__move_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
