// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 23c998e2207bd2bc

import { callMCPToolTyped } from "codegen/runtime";

export interface ReadMultipleFilesParams Record<string, unknown>

export interface ReadMultipleFilesResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "read_multiple_files",
  description: "Read the contents of multiple files simultaneously. This is more efficient than reading files one by one when you need to analyze or compare multiple files. Each file's content is returned with its path as a reference. Failed reads for individual files won't stop the entire operation. Only works within allowed directories."
};

/**
 * Read the contents of multiple files simultaneously. This is more efficient than reading files one by one when you need to analyze or compare multiple files. Each file's content is returned with its path as a reference. Failed reads for individual files won't stop the entire operation. Only works within allowed directories.
 */
export async function readMultipleFiles(params: ReadMultipleFilesParams): Promise<ReadMultipleFilesResult> {
  return callMCPToolTyped<ReadMultipleFilesParams, ReadMultipleFilesResult>("filesystem__read_multiple_files", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
