// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: ca62bd0a350a1347

import { callMCPToolTyped } from "codegen/runtime";

export interface ReadMediaFileParams Record<string, unknown>

export interface ReadMediaFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "read_media_file",
  description: "Read an image or audio file. Returns the base64 encoded data and MIME type. Only works within allowed directories."
};

/**
 * Read an image or audio file. Returns the base64 encoded data and MIME type. Only works within allowed directories.
 */
export async function readMediaFile(params: ReadMediaFileParams): Promise<ReadMediaFileResult> {
  return callMCPToolTyped<ReadMediaFileParams, ReadMediaFileResult>("filesystem__read_media_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
