// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: f2f4a774e2fb34c2

import { callMCPToolTyped } from "codegen/runtime";

export interface ReadTextFileParams Record<string, unknown>

export interface ReadTextFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "read_text_file",
  description: "Read the complete contents of a file from the file system as text. Handles various text encodings and provides detailed error messages if the file cannot be read. Use this tool when you need to examine the contents of a single file. Use the 'head' parameter to read only the first N lines of a file, or the 'tail' parameter to read only the last N lines of a file. Operates on the file as text regardless of extension. Only works within allowed directories."
};

/**
 * Read the complete contents of a file from the file system as text. Handles various text encodings and provides detailed error messages if the file cannot be read. Use this tool when you need to examine the contents of a single file. Use the 'head' parameter to read only the first N lines of a file, or the 'tail' parameter to read only the last N lines of a file. Operates on the file as text regardless of extension. Only works within allowed directories.
 */
export async function readTextFile(params: ReadTextFileParams): Promise<ReadTextFileResult> {
  return callMCPToolTyped<ReadTextFileParams, ReadTextFileResult>("filesystem__read_text_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
