// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: b3ac8466dfa093e4

import { callMCPToolTyped } from "codegen/runtime";

export interface ReadFileParams Record<string, unknown>

export interface ReadFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "read_file",
  description: "Read the complete contents of a file as text. DEPRECATED: Use read_text_file instead."
};

/**
 * Read the complete contents of a file as text. DEPRECATED: Use read_text_file instead.
 */
export async function readFile(params: ReadFileParams): Promise<ReadFileResult> {
  return callMCPToolTyped<ReadFileParams, ReadFileResult>("filesystem__read_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
