// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 66d70e35ad26bae6

import { callMCPToolTyped } from "codegen/runtime";

export interface SearchFilesParams Record<string, unknown>

export interface SearchFilesResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "search_files",
  description: "Recursively search for files and directories matching a pattern. Searches through all subdirectories from the starting path. The search is case-insensitive and matches partial names. Returns full paths to all matching items. Great for finding files when you don't know their exact location. Only searches within allowed directories."
};

/**
 * Recursively search for files and directories matching a pattern. Searches through all subdirectories from the starting path. The search is case-insensitive and matches partial names. Returns full paths to all matching items. Great for finding files when you don't know their exact location. Only searches within allowed directories.
 */
export async function searchFiles(params: SearchFilesParams): Promise<SearchFilesResult> {
  return callMCPToolTyped<SearchFilesParams, SearchFilesResult>("filesystem__search_files", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
