// AUTO-GENERATED BY mcp-codegen v1.0.1
// DO NOT EDIT BELOW THIS LINE
// hash: 940d4210c6b7e8ec

import { callMCPToolTyped } from "codegen/runtime";

export interface WriteFileParams Record<string, unknown>

export interface WriteFileResult Record<string, unknown>

export const toolMeta = {
  server: "filesystem",
  name: "write_file",
  description: "Create a new file or completely overwrite an existing file with new content. Use with caution as it will overwrite existing files without warning. Handles text content with proper encoding. Only works within allowed directories."
};

/**
 * Create a new file or completely overwrite an existing file with new content. Use with caution as it will overwrite existing files without warning. Handles text content with proper encoding. Only works within allowed directories.
 */
export async function writeFile(params: WriteFileParams): Promise<WriteFileResult> {
  return callMCPToolTyped<WriteFileParams, WriteFileResult>("filesystem__write_file", params);
}

// END AUTO-GENERATED

/* USER-EDITABLE AREA BELOW */
